params:
  seed: 42

  # environment wrapper clipping
  # NOTE: found these values by running analyze_ppo_actions_simple.py and overestimating so it never actually clips
  # all the real clipping should be handled way before
  # real max actions was like 15 and observation was like 25
  env:
    clip_observations: 5.0
    clip_actions: 1.0

  algo: 
    name: sac_utd

  model:
    name: soft_actor_critic

  network:
    name: sac_critic_layernorm
    separate: True
    critic_normalization: layer_norm
    actor_normalization: null

    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True

    mlp:
      units: [512, 256, 128]
      activation: relu
      d2rl: False

      initializer:
        name: default
    log_std_bounds: [-5, 2]

  load_checkpoint: False
  load_path: ''

  config:
    name: rlgames_cube_sac_utd
    device: 'cuda:0'
    device_name: 'cuda:0'
    env_name: rlgpu
    multi_gpu: False
    normalize_input: True
    reward_shaper:
      scale_value: 1.0
    max_epochs: 50000
    num_steps_per_episode: 100
    save_best_after: 100
    save_frequency: 1000
    gamma: 0.99
    init_alpha: 1.0
    alpha_lr: 0.005
    actor_lr: 0.0005
    critic_lr: 0.0005
    critic_tau: 0.005
    batch_size: 4096
    target_entropy_coef: 1.0
    learnable_temperature: true
    num_seed_steps: 5
    num_warmup_steps: 0
    replay_buffer_size: 1000000
    num_actors: -1  # configured from the script (based on num_envs)

    # UTD (Update-to-Data) ratio configuration
    utd_ratio: 1.0  # Can be < 1.0 (e.g., 0.5) or > 1.0 (e.g., 2.0, 4.0)

    player:
      #render: True
      deterministic: True
      games_num: 100000
      print_stats: True
